### ISSUE TITLE
Cannot Convert Ellipsis to Tensor

### ISSUE THREAD

**Issue by chasehere** [daavoo/kaggle_solutions#1]
I get an error when initiating the ResNet50 model.

```
#%%time
model = ResNet50(input_shape=(224,224,3), weights_path="data/resnet50_weights_tf_dim_ordering_tf_kernels_notop.h5")
```

gives:
```
---------------------------------------------------------------------------
AsTensorError                             Traceback (most recent call last)
<ipython-input-3-1a1296871c69> in <module>()
      1 #%%time
----> 2 model = ResNet50(input_shape=(224,224,3), weights_path="data/resnet50_weights_tf_dim_ordering_tf_kernels_notop.h5")

...

    206         except Exception:
    207             str_x = repr(x)
--> 208         raise AsTensorError("Cannot convert %s to TensorType" % str_x, type(x))
    209 
    210 # this has a different name, because _as_tensor_variable is the

AsTensorError: ('Cannot convert Ellipsis to TensorType', <type 'ellipsis'>)
```

I'm using Theano backend here but I get the same error with TensorFlow (they are worded a little differently).  What version of TensorFlow/numpy/python/keras are you using?  I have tensorflow=0.12.1, numpy=1.11.1, python=2.7.12, keras=1.2.1.

**Comment by daavoo** [comment]
HI @chasehere , that seems to be a problem with the Theano backend and the use of numpy syntaxis to extend the dimensions of a Tensor ([check issue here](https://github.com/Theano/Theano/issues/4539)). 

Can you confirm me that you are still getting this error when using Tensorflow backend???.

[Check this steps](https://keras.io/backend/) in keras to ensure that you are switching the backend correctly because it can be a little triky.

**Comment by daavoo** [comment]
By the way this was created and checked in Python 3.

**Comment by chasehere** [comment]
Thank you for the response!

I had done 
```
conda install tensorflow
```
which produced tf version=0.10.0rc0.  That version does not have Ellipsis support yet.  I was able to fix by uninstalling and using pip to get version 0.12.1 (and using Python 3).
```
conda uninstall tensorflow
pip install tensorflow
```

**Comment by wooblargl** [comment]
Is there a way to rewrite this with other numpy methods? Theano's missing support for `[...]` indexing is apparently the only thing blocking the use of Theano.

**Comment by daavoo** [comment]
@wooblargl You can replace it with:

```python
def vgg_preprocess(x):
    x = x - np.array([123.68, 116.779, 103.939], dtype=np.float32).reshape((1,1,3))
    return x
```
However you have to take in account another subtleties in order to use the same code in Theano; for example  the Batchnormalization axis and  the input_shape.

I rewrited the resnet50 model from scracth and with only Tensorflow support as an exercise to check my understanding of the architecture and because I don't like the Theano Channel / row / col order.

You can find a quite similar version of the model with both Theano and Tensorflow support (includes a little more boilerplate) here:
https://github.com/fchollet/deep-learning-models/blob/master/resnet50.py

If you just want to "use" the model use that. If you want to uderstand the model I'd recommend you to try to rewrite from scratch with Theano support.
